import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Worlds in Collision",
  description: "Generated by Auto Sense",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
